/*
 * TradersRoom Partner API
 * An API that combines with the Trades Room Center.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: suzumura@rnrnstar.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ProgramMembers model module.
 * @module model/ProgramMembers
 * @version 1.0.0
 */
export class ProgramMembers {
  /**
   * Constructs a new <code>ProgramMembers</code>.
   * @alias module:model/ProgramMembers
   * @class
   * @param programId {String} 
   * @param memberId {String} 
   */
  constructor(programId, memberId) {
    this.programId = programId;
    this.memberId = memberId;
  }

  /**
   * Constructs a <code>ProgramMembers</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProgramMembers} obj Optional instance to populate.
   * @return {module:model/ProgramMembers} The populated <code>ProgramMembers</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProgramMembers();
      if (data.hasOwnProperty('programId'))
        obj.programId = ApiClient.convertToType(data['programId'], 'String');
      if (data.hasOwnProperty('memberId'))
        obj.memberId = ApiClient.convertToType(data['memberId'], 'String');
      if (data.hasOwnProperty('accountNumber'))
        obj.accountNumber = ApiClient.convertToType(data['accountNumber'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} programId
 */
ProgramMembers.prototype.programId = undefined;

/**
 * @member {String} memberId
 */
ProgramMembers.prototype.memberId = undefined;

/**
 * @member {String} accountNumber
 */
ProgramMembers.prototype.accountNumber = undefined;

/**
 * @member {String} email
 */
ProgramMembers.prototype.email = undefined;

