/*
 * TradersRoom Partner API
 * An API that combines with the Trades Room Center.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: suzumura@rnrnstar.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Trader model module.
 * @module model/Trader
 * @version 1.0.0
 */
export class Trader {
  /**
   * Constructs a new <code>Trader</code>.
   * @alias module:model/Trader
   * @class
   * @param memberId {String} 
   * @param programId {String} 
   * @param email {String} 
   * @param name {String} 
   */
  constructor(memberId, programId, email, name) {
    this.memberId = memberId;
    this.programId = programId;
    this.email = email;
    this.name = name;
  }

  /**
   * Constructs a <code>Trader</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Trader} obj Optional instance to populate.
   * @return {module:model/Trader} The populated <code>Trader</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Trader();
      if (data.hasOwnProperty('memberId'))
        obj.memberId = ApiClient.convertToType(data['memberId'], 'String');
      if (data.hasOwnProperty('programId'))
        obj.programId = ApiClient.convertToType(data['programId'], 'String');
      if (data.hasOwnProperty('projectId'))
        obj.projectId = ApiClient.convertToType(data['projectId'], 'String');
      if (data.hasOwnProperty('trackingId'))
        obj.trackingId = ApiClient.convertToType(data['trackingId'], 'String');
      if (data.hasOwnProperty('accountNumber'))
        obj.accountNumber = ApiClient.convertToType(data['accountNumber'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} memberId
 */
Trader.prototype.memberId = undefined;

/**
 * @member {String} programId
 */
Trader.prototype.programId = undefined;

/**
 * @member {String} projectId
 */
Trader.prototype.projectId = undefined;

/**
 * @member {String} trackingId
 */
Trader.prototype.trackingId = undefined;

/**
 * @member {String} accountNumber
 */
Trader.prototype.accountNumber = undefined;

/**
 * @member {String} email
 */
Trader.prototype.email = undefined;

/**
 * @member {String} name
 */
Trader.prototype.name = undefined;

