/*
 * TradersRoom Partner API
 * An API that combines with the Trades Room Center.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: suzumura@rnrnstar.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TraderReport model module.
 * @module model/TraderReport
 * @version 1.0.0
 */
export class TraderReport {
  /**
   * Constructs a new <code>TraderReport</code>.
   * @alias module:model/TraderReport
   * @class
   * @param programId {String} 
   */
  constructor(programId) {
    this.programId = programId;
  }

  /**
   * Constructs a <code>TraderReport</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TraderReport} obj Optional instance to populate.
   * @return {module:model/TraderReport} The populated <code>TraderReport</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TraderReport();
      if (data.hasOwnProperty('programId'))
        obj.programId = ApiClient.convertToType(data['programId'], 'String');
      if (data.hasOwnProperty('accountNumber'))
        obj.accountNumber = ApiClient.convertToType(data['accountNumber'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('lot'))
        obj.lot = ApiClient.convertToType(data['lot'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} programId
 */
TraderReport.prototype.programId = undefined;

/**
 * @member {String} accountNumber
 */
TraderReport.prototype.accountNumber = undefined;

/**
 * @member {Number} amount
 */
TraderReport.prototype.amount = undefined;

/**
 * @member {Number} lot
 */
TraderReport.prototype.lot = undefined;

