/*
 * TradersRoom Partner API
 * An API that combines with the Trades Room Center.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: suzumura@rnrnstar.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {TokenItem} from '../model/TokenItem';

/**
* Token service.
* @module api/TokenApi
* @version 1.0.0
*/
export class TokenApi {

    /**
    * Constructs a new TokenApi. 
    * @alias module:api/TokenApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the tokenGet operation.
     * @callback moduleapi/TokenApi~tokenGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TokenItem{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * You can create access tokens for your program.
     * @param {String} programId Program&#x27;s unique identification ID
     * @param {String} jti Unique identifier for JWT. Used to prevent JWT replays
     * @param {module:api/TokenApi~tokenGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    tokenGet(programId, jti, callback) {
      
      let postBody = null;
      // verify the required parameter 'programId' is set
      if (programId === undefined || programId === null) {
        throw new Error("Missing the required parameter 'programId' when calling tokenGet");
      }
      // verify the required parameter 'jti' is set
      if (jti === undefined || jti === null) {
        throw new Error("Missing the required parameter 'jti' when calling tokenGet");
      }

      let pathParams = {
        
      };
      let queryParams = {
        'programId': programId,'jti': jti
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TokenItem;

      return this.apiClient.callApi(
        '/token', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}