/*
 * TradersRoom Partner API
 * An API that combines with the Trades Room Center.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: suzumura@rnrnstar.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {SuccessResponse} from '../model/SuccessResponse';
import {Trader} from '../model/Trader';

/**
* Trader service.
* @module api/TraderApi
* @version 1.0.0
*/
export class TraderApi {

    /**
    * Constructs a new TraderApi. 
    * @alias module:api/TraderApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the traderPost operation.
     * @callback moduleapi/TraderApi~traderPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SuccessResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * It is possible to create a new trader.
     * @param {module:model/Trader} body 
     * @param {module:api/TraderApi~traderPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    traderPost(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling traderPost");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SuccessResponse;

      return this.apiClient.callApi(
        '/trader', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the updateTrader operation.
     * @callback moduleapi/TraderApi~updateTraderCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SuccessResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Trader data can be updated.
     * @param {module:model/Trader} body 
     * @param {module:api/TraderApi~updateTraderCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    updateTrader(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateTrader");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SuccessResponse;

      return this.apiClient.callApi(
        '/trader', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}