/*
 * TradersRoom Partner API
 * An API that combines with the Trades Room Center.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: suzumura@rnrnstar.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TradersRoomPartnerApi);
  }
}(this, function(expect, TradersRoomPartnerApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SuccessResponse', function() {
      beforeEach(function() {
        instance = new TradersRoomPartnerApi.SuccessResponse();
      });

      it('should create an instance of SuccessResponse', function() {
        // TODO: update the code to test SuccessResponse
        expect(instance).to.be.a(TradersRoomPartnerApi.SuccessResponse);
      });

      it('should have the property success (base name: "success")', function() {
        // TODO: update the code to test the property success
        expect(instance).to.have.property('success');
        // expect(instance.success).to.be(expectedValueLiteral);
      });

    });
  });

}));
