/*
 * TradersRoom Partner API
 * An API that combines with the Trades Room Center.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: suzumura@rnrnstar.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TradersRoomPartnerApi);
  }
}(this, function(expect, TradersRoomPartnerApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TraderReport', function() {
      beforeEach(function() {
        instance = new TradersRoomPartnerApi.TraderReport();
      });

      it('should create an instance of TraderReport', function() {
        // TODO: update the code to test TraderReport
        expect(instance).to.be.a(TradersRoomPartnerApi.TraderReport);
      });

      it('should have the property programId (base name: "programId")', function() {
        // TODO: update the code to test the property programId
        expect(instance).to.have.property('programId');
        // expect(instance.programId).to.be(expectedValueLiteral);
      });

      it('should have the property accountNumber (base name: "accountNumber")', function() {
        // TODO: update the code to test the property accountNumber
        expect(instance).to.have.property('accountNumber');
        // expect(instance.accountNumber).to.be(expectedValueLiteral);
      });

      it('should have the property amount (base name: "amount")', function() {
        // TODO: update the code to test the property amount
        expect(instance).to.have.property('amount');
        // expect(instance.amount).to.be(expectedValueLiteral);
      });

      it('should have the property lot (base name: "lot")', function() {
        // TODO: update the code to test the property lot
        expect(instance).to.have.property('lot');
        // expect(instance.lot).to.be(expectedValueLiteral);
      });

    });
  });

}));
