/*
 * TradersRoom Partner API
 * An API that combines with the Trades Room Center.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: suzumura@rnrnstar.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {ProgramMembers} from './model/ProgramMembers';
import {SuccessResponse} from './model/SuccessResponse';
import {TokenItem} from './model/TokenItem';
import {Trader} from './model/Trader';
import {TraderReport} from './model/TraderReport';
import {ProgramMembersApi} from './api/ProgramMembersApi';
import {TokenApi} from './api/TokenApi';
import {TraderApi} from './api/TraderApi';
import {TraderReportApi} from './api/TraderReportApi';

/**
* An_API_that_combines_with_the_Trades_Room_Center_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TradersRoomPartnerApi = require('index'); // See note below*.
* var xxxSvc = new TradersRoomPartnerApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TradersRoomPartnerApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TradersRoomPartnerApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TradersRoomPartnerApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ProgramMembers model constructor.
     * @property {module:model/ProgramMembers}
     */
    ProgramMembers,

    /**
     * The SuccessResponse model constructor.
     * @property {module:model/SuccessResponse}
     */
    SuccessResponse,

    /**
     * The TokenItem model constructor.
     * @property {module:model/TokenItem}
     */
    TokenItem,

    /**
     * The Trader model constructor.
     * @property {module:model/Trader}
     */
    Trader,

    /**
     * The TraderReport model constructor.
     * @property {module:model/TraderReport}
     */
    TraderReport,

    /**
    * The ProgramMembersApi service constructor.
    * @property {module:api/ProgramMembersApi}
    */
    ProgramMembersApi,

    /**
    * The TokenApi service constructor.
    * @property {module:api/TokenApi}
    */
    TokenApi,

    /**
    * The TraderApi service constructor.
    * @property {module:api/TraderApi}
    */
    TraderApi,

    /**
    * The TraderReportApi service constructor.
    * @property {module:api/TraderReportApi}
    */
    TraderReportApi
};
